### ISSUE TITLE
Extension does not support generate change log

### ISSUE THREAD

**Issue by rduncan** [inergynl/liquibase-netezza#1]
Hi - I'm attempting to use your Netezza extension and I am getting the following error when attempting to generate a change log:

liquibase.exception.LiquibaseException: Unexpected error running Liquibase: liquibase.exception.UnexpectedLiquibaseException: Don't know how to query for sequences on USER@ jdbc:netezza://host:5480/database (Default Schema: ADMIN)

This traces back to a class that appears to need to be extended.  Have you run into this?

**Comment by ctessels** [comment]
I've looked into this and you're right about a class needed to be extended.
I'm guessing you were trying to create a snapshot.

Unfortunately i'm not able to create a Netezza implementation for this.
Netezza itself doesn't provide enough details about the sequences to generate a useful snapshot for them.
The SEQUENCES view pretty much returns null on all columns.

The definition of the SEQUENCES view:
```
SELECT
  DEFINITION_SCHEMA."_V_SEQUENCE"."DATABASE" AS SEQUENCE_CATALOG,
  DEFINITION_SCHEMA."_V_SEQUENCE"."SCHEMA"   AS SEQUENCE_SCHEMA,
  DEFINITION_SCHEMA."_V_SEQUENCE".SEQNAME    AS SEQUENCE_NAME,
  NULL :: UNKNOWN                            AS DATA_TYPE,
  NULL :: UNKNOWN                            AS NUMERIC_PRECISION,
  NULL :: UNKNOWN                            AS NUMERIC_PRECISION_RADIX,
  NULL :: UNKNOWN                            AS NUMERIC_SCALE,
  NULL :: UNKNOWN                            AS START_VALUE,
  NULL :: UNKNOWN                            AS MINIMUM_VALUE,
  NULL :: UNKNOWN                            AS MAXIMUM_VALUE,
  NULL :: UNKNOWN                            AS "INCREMENT",
  NULL :: UNKNOWN                            AS CYCLE_OPTION,
  NULL :: UNKNOWN                            AS DECLARED_DATA_TYPE,
  NULL :: UNKNOWN                            AS DECLARED_NUMERIC_PRECISION,
  NULL :: UNKNOWN                            AS DECLARED_NUMERIC_SCALE
FROM DEFINITION_SCHEMA."_V_SEQUENCE";
```
